### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'makeblastdb'

### ISSUE THREAD

**Issue by wdecoster** [mehrdadbakhtiari/adVNTR#14]
I right now don't have the time to investigate this further but I already wanted to report the error.

It's perhaps a dependency that needs to be installed?

```
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 1066443 reads
Traceback (most recent call last):
  File "advntr.py", line 60, in <module>
    run_advntr()
  File "advntr.py", line 49, in run_advntr
    genotype(args, genotype_parser)
  File "/home/wdecoster/bin/adVNTR/src/advntr_commands.py", line 73, in genotype
    genome_analyzier.find_repeat_counts_from_alignment_file(input_file)
  File "/home/wdecoster/bin/adVNTR/src/genome_analyzer.py", line 71, in find_repeat_counts_from_alignment_file
    vntr_reads = self.get_vntr_filtered_reads_map(unmapped_reads_file)
  File "/home/wdecoster/bin/adVNTR/src/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/wdecoster/bin/adVNTR/src/genome_analyzer.py", line 33, in get_vntr_filtered_reads_map
    read_ids = self.vntr_finder[vid].filter_reads_with_keyword_matching(self.working_dir, read_file, illumina)
  File "/home/wdecoster/bin/adVNTR/src/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/wdecoster/bin/adVNTR/src/vntr_finder.py", line 88, in filter_reads_with_keyword_matching
    empty_db = make_blast_database(read_file, blast_db_name)
  File "/home/wdecoster/bin/adVNTR/src/blast_wrapper.py", line 13, in make_blast_database
    call(['makeblastdb'] + make_db_args)
  File "/home/wdecoster/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/wdecoster/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/wdecoster/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'makeblastdb'
```

Cheers,
Wouter

**Comment by mehrdadbakhtiari** [comment]
Hi Wouter,

Is ncbi-blast (version 2.2.29 or above) is installed? It seems that the program cannot find `makeblastdb`, which is one the blast's scripts. Let me know if makeblastdb is available in the path but the problem exists.

Best,
Mehrdad

**Comment by wdecoster** [comment]
Uh I missed point 3 in the dependencies :-)

> In addition, ncbi-blast version 2.2.29 or above is required

I happily installed dependencies but missed this one. So this is not an issue. Sorry!
