### ISSUE TITLE
advntr not working with hg19_genic_VNTRs.db

### ISSUE THREAD

**Issue by philt31** [mehrdadbakhtiari/adVNTR#21]
Got advntr working through conda eg:
advntr genotype --alignment_file NS5_NA12878-PcrFree-Hg19-BWA_chr20.bam --working_directory ./log_dir/  -of bed -o NS5_NA12878-PcrFree-Hg19-BWA_chr20_VNTRstandard.bed

this works fine, however giving advntr bigger db (hg19_genic_VNTRs.db) as described in readme produces following error:
advntr genotype --alignment_file ../NS5_NA12878-PcrFree-Hg19-BWA_chr20.bam --working_directory ./log_dir/ -m ./vntr_data/hg19_genic_VNTRs.db

None
70183
None
70184
None
70185
None
Traceback (most recent call last):
  File "/home/ptedder/anaconda2/envs/ariba371/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/__main__.py", line 128, in main
    genotype(args, genotype_parser)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/advntr_commands.py", line 121, in genotype
    genome_analyzier.find_repeat_counts_from_alignment_file(input_file, average_coverage, args.update)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/genome_analyzer.py", line 129, in find_repeat_counts_from_alignment_file
    average_coverage, update)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/vntr_finder.py", line 681, in find_repeat_count_from_alignment_file
    return self.get_ru_count_with_coverage_method(pattern_occurrences, total_counted_vntr_bp, average_coverage)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/ptedder/anaconda2/envs/ariba371/lib/python3.6/site-packages/advntr/vntr_finder.py", line 624, in get_ru_count_with_coverage_method
    estimate = [int(pattern_occurrences / (float(average_coverage) * haplotypes))] * 2
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by mehrdadbakhtiari** [comment]
Thank you for reporting this problem and sorry for the inconvenience. Commit d208428 should solve the problem.
You can use the updated code from github right now. For conda, the tests take a little bit of time and the conda version should be available in a few hours at the latest.

**Comment by philt31** [comment]
Hello,
I've given it a go today. I created a fresh conda environment and installed advntr with the following cmd:
advntr genotype --alignment_file ../NS5_NA12878-PcrFree-Hg19-BWA_chr20.bam --working_directory ./log_dir/ -m ./vntr_data/hg19_genic_VNTRs.db -o advntr_hg19_genic_VNTRs.out2

unofrtunately its now core dumping here are the last lines of the output file:
8948
None
8967
None
8968
None
8975
None
8976
None

and last lines of log dir:
2019-06-20 16:36:23,175 DEBUG:vntr base pairs in mapped reads: 0
2019-06-20 16:36:23,175 INFO:select_illumina_reads executed in 0.020758s
2019-06-20 16:36:23,176 INFO:covered repeats: []
2019-06-20 16:36:23,176 INFO:flanking repeats: []
2019-06-20 16:36:23,176 INFO:Maximum probability for genotyping: 1e-20
2019-06-20 16:36:23,176 INFO:RU count lower bounds: None
2019-06-20 16:36:23,191 INFO:find_repeat_count_from_alignment_file executed in 0.036397s
2019-06-20 16:36:23,191 DEBUG:finding repeat count from alignment file for 8976
2019-06-20 16:36:23,201 DEBUG:vntr base pairs in unmapped reads: 0.0
2019-06-20 16:36:23,212 DEBUG:vntr base pairs in mapped reads: 0
2019-06-20 16:36:23,213 INFO:select_illumina_reads executed in 0.021775s
2019-06-20 16:36:23,213 INFO:covered repeats: []
2019-06-20 16:36:23,213 INFO:flanking repeats: []
2019-06-20 16:36:23,214 INFO:Maximum probability for genotyping: 1e-20
2019-06-20 16:36:23,214 INFO:RU count lower bounds: None
2019-06-20 16:36:23,228 INFO:find_repeat_count_from_alignment_file executed in 0.037569s
2019-06-20 16:36:23,228 DEBUG:finding repeat count from alignment file for 8977
2019-06-20 16:36:23,239 DEBUG:vntr base pairs in unmapped reads: 0.0

I tried then installing it manually from git both on our cluster (i couldn't find a configure file to make it install in my home dir so this didnt work). tried it on my mac but it looks like I'm having cython problems:
pomegranate/distributions.pyx:2226:73: Converting to Python object not allowed without gil
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    ext_modules=cythonize(["pomegranate/*.pyx"]),
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pomegranate/distributions.pyx

**Comment by philt31** [comment]
This is the fault adVNTR is now producing

sh: line 1:  4273 Segmentation fault      (core dumped) adVNTR-Filtering ./log_dir//NS5_NA12878-PcrFree-Hg19-BWA_chr20.unmapped.fasta < ./log_dir///keywords_NS5_NA12878-PcrFree-Hg19-BWA_chr20.unmapped.fasta.txt > ./log_dir//filtering_out_NS5_NA12878-PcrFree-Hg19-BWA_chr20.unmapped.fasta.txt

**Comment by mehrdadbakhtiari** [comment]
Does the program continue to run and write to `advntr_hg19_genic_VNTRs.out2` even after writing the Segmentation fault error? If this is the case, commit 9beddbf should solve the problem. I have also submitted the revision to conda.
If you want to use it sooner than bioconda revision, you can to get the code from github and run `make`, and then copy `adVNTR-Filtering` to the binary path. (You can find the path by writing `which adVNTR-Filtering`, which is somewhere in your conda directory). You don't need to manually install the python package as this commit only changes `adVNTR-Filtering`.

Could you please check the version of cython on your mac? It seems that the cython problem could be solved using newer cython.

Thanks for your reports.
