### ISSUE TITLE
cannot create my custom database

### ISSUE THREAD

**Issue by jxlabWzZ** [mehrdadbakhtiari/adVNTR#22]
hi, i installed the latest version of adVNTR （v1.32） using miniconda: conda install -c bioconda advntr, and erverything is well but i cannot add (create) a new .db
ohh! i created a new folder : vntr_data

my code is : 
advntr addmodel -r sus.fa -p GGGGTCATG -s 14859 -e 14889 -c chr1

error info:
Traceback (most recent call last):
  File "/home/miniconda2/envs/py36/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/__main__.py", line 138, in main
    add_model(args, addmodel_parser)
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/advntr_commands.py", line 184, in add_model
    create_vntrs_database(settings.TRAINED_MODELS_DB)
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/models.py", line 115, in create_vntrs_database
    ''')
sqlite3.OperationalError: disk I/O error

it will generate a new file (hg19_selected_VNTRs_Illumina.db) under vntr_data, if change the permission to 777 (chmod 777 *)
,another error encounterd:

Traceback (most recent call last):
  File "/home/miniconda2/envs/py36/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/__main__.py", line 138, in main
    add_model(args, addmodel_parser)
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/advntr_commands.py", line 186, in add_model
    vntr_id = get_largest_id_in_database() + 1
  File "/home/miniconda2/envs/py36/lib/python3.6/site-packages/advntr/models.py", line 207, in get_largest_id_in_database
    cursor.execute('''SELECT MAX(id) FROM vntrs''')
sqlite3.OperationalError: disk I/O error

although，I saw the same question, I didn't get any exact solution。
Thank you in advance

**Comment by mehrdadbakhtiari** [comment]
Hello,

Could you try to run `advntr addmodel -r sus.fa -p GGGGTCATG -s 14859 -e 14889 -c chr1 -m my_db.db`? without `-m` parameter it tries to create the database in a default directory to which you may not have access. (This will solve your first problem)
Also, can you check the access permission of "hg19_selected_VNTRs_Illumina.db" or my_db.db (in case you specified the name) after getting the second error?

**Comment by jxlabWzZ** [comment]
Thank you for your reply.

If i run: advntr addmodel -r sus.fa -p GGGGTCATG -s 14859 -e 14889 -c chr1
it will generate a file under vntr_data/ ,the access is:
-rw-r--r--    1    useid    useid    0    Nov     8    11:12    hg19_selected_VNTRs_Illumina.db
and the error info is:
Traceback (most recent call last):
  File "/home/miniconda3/envs/str/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/__main__.py", line 138, in main
    add_model(args, addmodel_parser)
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/advntr_commands.py", line 184, in add_mode
    create_vntrs_database(settings.TRAINED_MODELS_DB)
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/models.py", line 118, in create_vntrs_data
    ''')
sqlite3.OperationalError: disk I/O error

If i run:advntr addmodel -r sus.fa -p GGGGTCATG -s 14859 -e 14889 -c chr1 -m my_db.db
no file or folder were generated
the error info is:

Traceback (most recent call last):
  File "/home/miniconda3/envs/str/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/__main__.py", line 138, in main
    add_model(args, addmodel_parser)
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/advntr_commands.py", line 184, in add_mode
    create_vntrs_database(settings.TRAINED_MODELS_DB)
  File "/home/miniconda3/envs/str/lib/python2.7/site-packages/advntr/models.py", line 112, in create_vntrs_data
    os.makedirs(os.path.dirname(db_file))
  File "/home/miniconda3/envs/str/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
nohup.out (END)

**Comment by Jong-hun-Park** [comment]
Hi,

I know that you've tried it many times, but could you please double-check in which folder you are running adVNTR?
As Mehrdad mentioned, if you run 'advntr addmodel' without -m parameter, it will generate a folder and file under wherever you launch adVNTR. I just want to make sure that we are looking at the same folder and file.
In addition to that, can you please let us know which OS are you trying to run on?
