### ISSUE TITLE
Can't run adVNTR genotype - unexpected keyword argument 'max_prob'

### ISSUE THREAD

**Issue by hevmarriott** [mehrdadbakhtiari/adVNTR#39]
Hi there, 

I have been trying to run adVNTR (latest version) via conda and every time it gives me this error: 

Traceback (most recent call last):

  File "/users/k19042397/miniconda2/envs/adVNTR/bin/advntr", line 11, in <modu$
    sys.exit(main())
  File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/ad$
    genotype(args, genotype_parser)
  File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/ad$
    genome_analyzier.find_repeat_counts_from_alignment_file(input_file, averag$
  File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/ad$
    average_coverage, update)
  File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/ad$
    retval = func(*args, **kwargs)
  File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/ad$
    max_prob=0)  # No probability for the estimated genotype
TypeError: __init__() got an unexpected keyword argument 'max_prob'

I do not know whether this is a disagreement between _init_ GenotypeResult, which does not have max_prob assigned and defined further down, only max_likelihood, or if it is a problem with my options. I assigned a float to the coverage option and played around with the options and it still gives me this. 

Any help would be much appreciated. 

All the best, 

Heather

**Comment by hevmarriott** [comment]
Hi 
Sorry, it seems it cut off most of the code

Here is the updated version: 

Traceback (most recent call last):

File "/users/k19042397/miniconda2/envs/adVNTR/bin/advntr", line 11, in <module>
sys.exit(main())
File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/advntr/__main__.py, line 134, in main
genotype(args, genotype_parser)
File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/advntr_commands.py, line 124, in genotype 
genome_analyzier.find_repeat_counts_from_alignment_file(input_file, average_coverage, update)
File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/advntr/genome_analyzer.py", line 241, in find_repeat_counts_from_alignment_file
average_coverage, update)
File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/advntr/profiler.py", line 8, in wrapper
retval = func(*args, **kwargs)
File "/users/k19042397/miniconda2/envs/adVNTR/lib/python3.6/site-packages/advntr/vntr_finder.py", line 750, in find_repeat_count_from_alignment_file
max_prob=0) # No probability for the estimated genotype
TypeError: init() got an unexpected keyword argument 'max_prob'
