### ISSUE TITLE
Error with genotype 

### ISSUE THREAD

**Issue by R-Laksh** [mehrdadbakhtiari/adVNTR#51]
Hi,

I've been trying to follow the quickstart guide to test adVNTR using the sample data provided. However, the following error keeps occuring

Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/bin/advntr", line 11, in <module>
    sys.exit(main())
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/__main__.py", line 134, in main
    genotype(args, genotype_parser)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/advntr_commands.py", line 124, in genotype
    genome_analyzier.find_repeat_counts_from_alignment_file(input_file, average_coverage, args.update)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/genome_analyzer.py", line 241, in find_repeat_counts_from_alignment_file
    average_coverage, update)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/vntr_finder.py", line 707, in find_repeat_count_from_alignment_file
    selected_reads = self.select_illumina_reads(alignment_file, unmapped_filtered_reads, update)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/vntr_finder.py", line 658, in select_illumina_reads
    hmm = self.get_vntr_matcher_hmm(read_length=read_length)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/vntr_finder.py", line 119, in get_vntr_matcher_hmm
    vntr_matcher = self.build_vntr_matcher_hmm(copies, flanking_region_size)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/vntr_finder.py", line 101, in build_vntr_matcher_hmm
    vntr_matcher = get_read_matcher_model(left_flanking_region, right_flanking_region, patterns, copies)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/hmm_utils.py", line 529, in get_read_matcher_model
    repeats_matcher = get_variable_number_of_repeats_matcher_hmm(patterns, copies, vpaths)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/hmm_utils.py", line 476, in get_variable_number_of_repeats_matcher_hmm
    model = get_constant_number_of_repeats_matcher_hmm(patterns, copies, vpaths)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/hmm_utils.py", line 405, in get_constant_number_of_repeats_matcher_hmm
    transitions, emissions = build_profile_hmm_for_repeats(patterns, settings.MAX_ERROR_RATE)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profiler.py", line 8, in wrapper
    retval = func(*args, **kwargs)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/advntr/profile_hmm.py", line 169, in build_profile_hmm_for_repeats
    stdout, stderr = muscle_cline(stdin=data)
  File "/home/users/astar/gis/ramul/miniconda3/envs/advntrenv/lib/python2.7/site-packages/Bio/Application/__init__.py", line 531, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -clwstrict', message 'Invalid command line'

command: advntr genotype --vntr_id 301645 --alignment_file CSTB_2_5_testdata.bam --working_directory working_dir

A similar error also occurs when running the addmodel command. I'm at quite a loss so any help would be deeply appreciated.

**Comment by ltf2020** [comment]
We also encountered similar errors
File "/home/luotf/miniconda3/envs/python27/bin/advntr", line 11, in <module>
    load_entry_point('advntr==1.4.1', 'console_scripts', 'advntr')()
  File "build/bdist.linux-x86_64/egg/advntr/__main__.py", line 134, in main
  File "build/bdist.linux-x86_64/egg/advntr/advntr_commands.py", line 124, in genotype
  File "build/bdist.linux-x86_64/egg/advntr/genome_analyzer.py", line 238, in find_repeat_counts_from_alignment_file
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 710, in find_repeat_count_from_alignment_file
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 660, in select_illumina_reads
  File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 119, in get_vntr_matcher_hmm
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 101, in build_vntr_matcher_hmm
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 529, in get_read_matcher_model
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 476, in get_variable_number_of_repeats_matcher_hmm
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 405, in get_constant_number_of_repeats_matcher_hmm
  File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper
  File "build/bdist.linux-x86_64/egg/advntr/profile_hmm.py", line 169, in build_profile_hmm_for_repeats
  File "/home/luotf/miniconda3/envs/python27/lib/python2.7/site-packages/Bio/Application/__init__.py", line 527, in __call__
    stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -clwstrict', message 'Invalid command line'

**Comment by Lionward** [comment]
> We also encountered similar errors File "/home/luotf/miniconda3/envs/python27/bin/advntr", line 11, in load_entry_point('advntr==1.4.1', 'console_scripts', 'advntr')() File "build/bdist.linux-x86_64/egg/advntr/**main**.py", line 134, in main File "build/bdist.linux-x86_64/egg/advntr/advntr_commands.py", line 124, in genotype File "build/bdist.linux-x86_64/egg/advntr/genome_analyzer.py", line 238, in find_repeat_counts_from_alignment_file File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 710, in find_repeat_count_from_alignment_file File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 660, in select_illumina_reads File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 119, in get_vntr_matcher_hmm File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/vntr_finder.py", line 101, in build_vntr_matcher_hmm File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 529, in get_read_matcher_model File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 476, in get_variable_number_of_repeats_matcher_hmm File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/hmm_utils.py", line 405, in get_constant_number_of_repeats_matcher_hmm File "build/bdist.linux-x86_64/egg/advntr/profiler.py", line 8, in wrapper File "build/bdist.linux-x86_64/egg/advntr/profile_hmm.py", line 169, in build_profile_hmm_for_repeats File "/home/luotf/miniconda3/envs/python27/lib/python2.7/site-packages/Bio/Application/**init**.py", line 527, in **call** stdout_str, stderr_str) Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -clwstrict', message 'Invalid command line'

did you  manage to solve this problem?

**Comment by Jong-hun-Park** [comment]
Can you try installing muscle?

```conda install muscle=3.8.1551```
