### ISSUE TITLE
Error running advntr --help

### ISSUE THREAD

**Issue by aravindpad** [mehrdadbakhtiari/adVNTR#68]
Hi,
I was trying to setup advntr using conda and running into to this error. Any help is appreciated.
Thank you

> (/home/aravind/advntrenv) aravind@cn61:~$ advntr --help
> Traceback (most recent call last):
>   File "/home/aravind/advntrenv/bin/advntr", line 7, in <module>
>     from advntr.__main__ import main
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/advntr/__main__.py", line 6, in <module>
>     from advntr.advntr_commands import genotype, view_model, add_model, del_model
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/advntr/advntr_commands.py", line 7, in <module>
>     from advntr.genome_analyzer import GenomeAnalyzer
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/advntr/genome_analyzer.py", line 8, in <module>
>     from advntr.vntr_finder import VNTRFinder
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/advntr/vntr_finder.py", line 14, in <module>
>     from advntr.hmm_utils import *
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/advntr/hmm_utils.py", line 3, in <module>
>     from pomegranate import DiscreteDistribution, State
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/pomegranate/__init__.py", line 38, in <module>
>     from .hmm import *
>   File "pomegranate/hmm.pyx", line 13, in init pomegranate.hmm
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/networkx/__init__.py", line 68, in <module>
>     import networkx.utils
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/networkx/utils/__init__.py", line 2, in <module>
>     from networkx.utils.decorators import *
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/networkx/utils/decorators.py", line 7, in <module>
>     from decorator import decorator
>   File "/home/aravind/advntrenv/lib/python2.7/site-packages/decorator.py", line 162
>     print('Error in generated code:', file=sys.stderr)
>                                           ^
> SyntaxError: invalid syntax
>

**Comment by aravindpad** [comment]
Hi,
Any help would be much appreciated.
Thanks

**Comment by aravindpad** [comment]
Hi,
Thank you for replying.
I am using Conda and the adVNTR version is 1.5.0 (I installed it on the day I opened the issue).
I have another user with the same issue (using Conda). Do we need to try source?
Thanks

**Comment by Jong-hun-Park** [comment]
What version of python do you use?
If you are using python 2.7 for adVNTR-1.5.0, can you try python 3.6?

**Comment by aravindpad** [comment]
Hi,
Thank you and apologies on the delayed response. With Python 3.6 I'm getting

`(/xxx/aravind/advntrenv) aravind@cn:/xxx/aravind/advntrenv$ conda install -c conda-forge -c bioconda advntr
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): \ Killed
(/xxx/aravind/advntrenv) aravind@cn:/xxxx/aravind/advntrenv$
`
Do you have any other repodata?
Thank you

**Comment by aravindpad** [comment]
Hi again,
With Python 3.5 I'm getting. Is there any way to get around this or installing form source is the only way.
Thanks

@xbwdk , I got the same issue with 3.8, that's why i tried 3.5. Got it installed but getting run-time issues.
Thanks
> ravind@cn105:~$ advntr --help
Traceback (most recent call last):
  File "/xxx/yy/advntrenv/bin/advntr", line 7, in <module>
    from advntr.__main__ import main
  File "/xxx/yy/advntrenv/lib/python3.5/site-packages/advntr/__main__.py", line 6, in <module>
    from advntr.advntr_commands import genotype, view_model, add_model, del_model
  File "/xxx/yy/advntrenv/lib/python3.5/site-packages/advntr/advntr_commands.py", line 7, in <module>
    from advntr.genome_analyzer import GenomeAnalyzer
  File "/xxx/yy/advntrenv/lib/python3.5/site-packages/advntr/genome_analyzer.py", line 7, in <module>
    from advntr.sam_utils import extract_unmapped_reads_to_fasta_file
  File "/xxx/yy/advntrenv/lib/python3.5/site-packages/advntr/sam_utils.py", line 1, in <module>
    import pysam
  File "/xxx/yy/advntrenv/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by Jong-hun-Park** [comment]
Can you please try the following?
```
git clone https://github.com/mehrdadbakhtiari/adVNTR
cd adVNTR
make; make install
python setup.py install
```

**Comment by aravindpad** [comment]
@Jong-hun-Park Will try and update here.
Thank you

**Comment by Jong-hun-Park** [comment]
Can you please try installing muscle first?
```
conda install muscle=3.8.1551
```
And, then try again with python 3.6

**Comment by aravindpad** [comment]
@Jong-hun-Park 
Thank you and sorry for a delayed reply.
Still having the same trouble
`Downloading and Extracting Packages
muscle-3.8.1551      | 262 KB    | ################################################################################################################################################################################################################################################################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Retrieving notices: ...working... done
(/home/aravind/advntrenv1) aravind@162:~$ conda install -c conda-forge -c bioconda advntr
Collecting package metadata (current_repodata.json): / WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1                                                                                                                                                        done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): - Killed
`
Thanks

**Comment by aravindpad** [comment]
@xbwdk 
Thank you. I just tried to install tensorflow and it went well as I'm using anaconda.
However, advntr still fails.

> conda list | grep -i tensor
> tensorboard               1.13.1           py36hf484d3e_0
> tensorflow                1.13.1          mkl_py36h27d456a_0
> tensorflow-base           1.13.1          mkl_py36h7ce6ba3_0
> tensorflow-estimator      1.13.0                     py_0
> (/home/aravind/advntrenv1) aravind@105:~$

It's failing at this point

> conda install -c conda-forge -c bioconda advntr
> Collecting package metadata (current_repodata.json): \ WARNING conda.models.version:get_matcher(542): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1                                                                                                                                                        done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): / Killed
> 

Thank you
