### ISSUE TITLE
addmodel error

### ISSUE THREAD

**Issue by BrendaLee1** [mehrdadbakhtiari/adVNTR#70]
Hi,
I tried to build database for my VNTRs, the following error occurred:
Traceback (most recent call last):
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/bin/advntr", line 33, in <module>
    sys.exit(load_entry_point('advntr==1.5.0', 'console_scripts', 'advntr')())
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/advntr-1.5.0-py3.10-linux-x86_64.egg/advntr/__main__.py", line 149, in main
    add_model(args, addmodel_parser)
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/advntr-1.5.0-py3.10-linux-x86_64.egg/advntr/advntr_commands.py", line 208, in add_model
    ref_vntr.init_from_vntrseek_data()
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/advntr-1.5.0-py3.10-linux-x86_64.egg/advntr/reference_vntr.py", line 45, in init_from_vntrseek_data
    repeat_segments = self.find_repeat_segments(corresponding_region_in_ref)
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/advntr-1.5.0-py3.10-linux-x86_64.egg/advntr/reference_vntr.py", line 82, in find_repeat_segments
    model = build_reference_repeat_finder_hmm(patterns, copies=self.estimated_repeats)
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/advntr-1.5.0-py3.10-linux-x86_64.egg/advntr/hmm_utils.py", line 674, in build_reference_repeat_finder_hmm
    model.bake()
  File "pomegranate/hmm.pyx", line 731, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/rd1/laixh/soft/anaconda2/envs/snakemake/lib/python3.10/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
KeyError: 0

Any Suggestion?

**Comment by Jong-hun-Park** [comment]
Hi @BrendaLee1 
Currently, adVNTR works only with python 3.6 or 2.7.
Please create a new conda envs with python 3.6 and install it again.
